// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchain.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	blockchain.proto

It has these top-level messages:
	AddBlockRequest
	AddBlockResponse
	Block
	GetBlockchainRequest
	GetBlockchainResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Datatype int32

const (
	Datatype_TEXT        Datatype = 0
	Datatype_TRANSACTION Datatype = 1
)

var Datatype_name = map[int32]string{
	0: "TEXT",
	1: "TRANSACTION",
}
var Datatype_value = map[string]int32{
	"TEXT":        0,
	"TRANSACTION": 1,
}

func (x Datatype) String() string {
	return proto1.EnumName(Datatype_name, int32(x))
}
func (Datatype) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AddBlockRequest struct {
	Data     string   `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Datatype Datatype `protobuf:"varint,2,opt,name=datatype,enum=proto.Datatype" json:"datatype,omitempty"`
}

func (m *AddBlockRequest) Reset()                    { *m = AddBlockRequest{} }
func (m *AddBlockRequest) String() string            { return proto1.CompactTextString(m) }
func (*AddBlockRequest) ProtoMessage()               {}
func (*AddBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddBlockRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *AddBlockRequest) GetDatatype() Datatype {
	if m != nil {
		return m.Datatype
	}
	return Datatype_TEXT
}

type AddBlockResponse struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *AddBlockResponse) Reset()                    { *m = AddBlockResponse{} }
func (m *AddBlockResponse) String() string            { return proto1.CompactTextString(m) }
func (*AddBlockResponse) ProtoMessage()               {}
func (*AddBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddBlockResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Block struct {
	Hash          string   `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	PrevBlockHash string   `protobuf:"bytes,2,opt,name=prevBlockHash" json:"prevBlockHash,omitempty"`
	Data          string   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Timestamp     int64    `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Datatype      Datatype `protobuf:"varint,5,opt,name=datatype,enum=proto.Datatype" json:"datatype,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto1.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *Block) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetDatatype() Datatype {
	if m != nil {
		return m.Datatype
	}
	return Datatype_TEXT
}

type GetBlockchainRequest struct {
}

func (m *GetBlockchainRequest) Reset()                    { *m = GetBlockchainRequest{} }
func (m *GetBlockchainRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetBlockchainRequest) ProtoMessage()               {}
func (*GetBlockchainRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetBlockchainResponse struct {
	Blocks []*Block `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *GetBlockchainResponse) Reset()                    { *m = GetBlockchainResponse{} }
func (m *GetBlockchainResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetBlockchainResponse) ProtoMessage()               {}
func (*GetBlockchainResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetBlockchainResponse) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto1.RegisterType((*AddBlockRequest)(nil), "proto.AddBlockRequest")
	proto1.RegisterType((*AddBlockResponse)(nil), "proto.AddBlockResponse")
	proto1.RegisterType((*Block)(nil), "proto.Block")
	proto1.RegisterType((*GetBlockchainRequest)(nil), "proto.GetBlockchainRequest")
	proto1.RegisterType((*GetBlockchainResponse)(nil), "proto.GetBlockchainResponse")
	proto1.RegisterEnum("proto.Datatype", Datatype_name, Datatype_value)
}

func init() { proto1.RegisterFile("blockchain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x5d, 0xd6, 0x76, 0x74, 0xdf, 0x9c, 0x2d, 0x41, 0x67, 0x99, 0x3b, 0x94, 0x32, 0xa5, 0x28,
	0xec, 0x50, 0xcf, 0x3b, 0x74, 0x2a, 0x2a, 0xc8, 0x84, 0xd8, 0x83, 0xd7, 0x6e, 0x0d, 0x74, 0xe8,
	0xd6, 0xba, 0x44, 0xc1, 0x9f, 0xe2, 0xcd, 0x9f, 0x2a, 0x4d, 0xd3, 0xd6, 0xce, 0xc2, 0x4e, 0x09,
	0xef, 0x3d, 0x5e, 0xde, 0x7b, 0x01, 0x73, 0xf1, 0x96, 0x2c, 0x5f, 0x97, 0x71, 0xb8, 0xda, 0x4c,
	0xd2, 0x6d, 0xc2, 0x13, 0xac, 0x89, 0xc3, 0x21, 0x60, 0xf8, 0x51, 0x34, 0xcb, 0x58, 0x42, 0xdf,
	0x3f, 0x28, 0xe3, 0x18, 0x83, 0x1a, 0x85, 0x3c, 0xb4, 0x90, 0x8d, 0xdc, 0x2e, 0x11, 0x77, 0x7c,
	0x09, 0x7a, 0x76, 0xf2, 0xaf, 0x94, 0x5a, 0x6d, 0x1b, 0xb9, 0x87, 0x9e, 0x91, 0xfb, 0x4c, 0x6e,
	0x24, 0x4c, 0x4a, 0x81, 0x73, 0x0e, 0x66, 0xe5, 0xc9, 0xd2, 0x64, 0xc3, 0x68, 0x66, 0x1a, 0x87,
	0x2c, 0x2e, 0x4c, 0xb3, 0xbb, 0xf3, 0x83, 0x40, 0x13, 0xaa, 0x26, 0x16, 0x8f, 0xa1, 0x9f, 0x6e,
	0xe9, 0xa7, 0x10, 0xdc, 0x67, 0x64, 0x5b, 0x90, 0x75, 0xb0, 0x0c, 0xab, 0xfc, 0x09, 0x3b, 0x82,
	0x2e, 0x5f, 0xad, 0x29, 0xe3, 0xe1, 0x3a, 0xb5, 0x54, 0x1b, 0xb9, 0x0a, 0xa9, 0x80, 0x5a, 0x15,
	0x6d, 0x5f, 0x95, 0x01, 0x1c, 0xdd, 0x51, 0x3e, 0x2b, 0xc7, 0x93, 0x1b, 0x39, 0x53, 0x38, 0xde,
	0xc1, 0x65, 0xcf, 0x31, 0x74, 0xc4, 0xd4, 0xcc, 0x42, 0xb6, 0xe2, 0xf6, 0xbc, 0x03, 0xe9, 0x9d,
	0xaf, 0x21, 0xb9, 0x8b, 0x33, 0xd0, 0x8b, 0xc7, 0xb0, 0x0e, 0x6a, 0x70, 0xfb, 0x12, 0x98, 0x2d,
	0x6c, 0x40, 0x2f, 0x20, 0xfe, 0xfc, 0xd9, 0xbf, 0x0e, 0x1e, 0x9e, 0xe6, 0x26, 0xf2, 0xbe, 0x11,
	0x40, 0xf5, 0x06, 0x9e, 0x82, 0x5e, 0xec, 0x8a, 0x07, 0xd2, 0x77, 0xe7, 0xf3, 0x86, 0x27, 0xff,
	0xf0, 0x3c, 0x98, 0xd3, 0xc2, 0x8f, 0xd0, 0xaf, 0x65, 0xc6, 0xa7, 0x52, 0xdb, 0xd4, 0x70, 0x38,
	0x6a, 0x26, 0x0b, 0xb7, 0x45, 0x47, 0xd0, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x55, 0x14,
	0x86, 0x84, 0x5a, 0x02, 0x00, 0x00,
}
